### ISSUE TITLE
Improve inference performance validation: tunable, per-accelerator params wired into recipes

### ISSUE THREAD

**Issue by yuanchen8911** [NVIDIA/aicr#1116]
## Summary

The `inference-perf` check defaulted to a tiny smoke-test model (Qwen/Qwen3-0.6B) with only global tuning knobs, so it couldn't characterize modern accelerators or adapt per GPU type. It is now **configurable per recipe**, backed by a **model-weights cache**, with **per-accelerator thresholds re-measured on real hardware** — so `aicr validate --phase performance` reflects GPU compute, not serving overhead, and works out of the box.

Implemented on branch `feat/inference-perf-configurable-model` (stacked on merged PR #1096); validated end to end on RTX PRO 6000, H100 (EKS + GKE), and GB200.

### 1. Per-recipe configuration

`inference-model` and `inference-concurrency-per-gpu` are now read from the recipe's `validation.performance.constraints` — symmetric with the `inference-throughput` / `inference-ttft-p99` thresholds that already live there. Each `<accel>-<service>-…-inference-dynamo` overlay pins its own values. Resolution precedence is **recipe constraint > catalog `env` (`AICR_INFERENCE_PERF_*`) > compiled default**. New defaults: **Qwen/Qwen3-8B at 256 concurrency/GPU** (the empirical throughput sweet spot across all tested accelerators).

### 2. Model-weights cache

A PVC-backed cache is **on by default**: a one-time populate Job downloads the model once, and all workers mount it read-only (`HF_HUB_OFFLINE=1`). This removes the per-worker Hugging Face download that tripped per-IP HTTP 429 throttling on large models, and needs no token for ungated models. Disable with `AICR_INFERENCE_PERF_MODEL_CACHE_SIZE=off`. The cache **fails fast** with actionable guidance when no StorageClass is resolvable (instead of leaving the PVC `Pending` until timeout); on EKS the `aws-ebs-csi-driver` component now provisions a default `gp3` StorageClass so it works zero-config (GKE already has `standard-rwo`).

### 3. Updated / improved thresholds

The per-accelerator gates (previously placeholders tuned to 0.6B at conc 16: `>= 5000` / `<= 200`) were re-measured at 8B / 256 and pinned alongside the model + concurrency in each overlay:

| Accelerator (overlay) | throughput gate | TTFT p99 gate | measured (8B/256) |
|---|---|---|---|
| RTX PRO 6000 (eks) | `>= 50000` | `<= 1000` | 59,260 tok/s · 445 ms · 100% util |
| H100 (eks + gke) | `>= 50000` | `<= 1000` | ~108k tok/s · ~700 ms · 100% util |
| GB200 (eks) | `>= 50000` | `<= 2000` | 65,952 tok/s · 1,240 ms · 80% util |
| B200 (gke) | `>= 50000` | `<= 2000` | untested — mirrors GB200 (flagged in-file) |

The evaluator applies a 10% tolerance on top of these.

## Remaining work

1. **Precision** (FP8 / NVFP4, typically via the checkpoint ID) — not yet a knob.
2. **Tensor-parallel size (TP > 1)** — the Dynamo deploy template still hardcodes TP=1 / one worker per GPU. Needed for models that exceed one GPU (e.g. 32B BF16 on an 80 GB H100) and to fully load a Blackwell GPU on GB200.

## Motivation (from 8B characterization)

At the original 0.6B size the benchmark was serving-overhead-bound and never loaded the GPU. Defaulting to **8B at 256 concurrency/GPU** fixes that on Hopper/Ada — H100 and RTX PRO 6000 reach **~100% GPU util** at their throughput peak. **GB200 reaches only ~80%** on 8B (it is over-provisioned for a model this small), which is what the remaining **precision + TP / larger-model** work is for. TTFT SLO context: interactive ~200 ms, voice ~500 ms, MLPerf server 2 s (70B) – 6 s (405B).

## Related

- PR #1096 (warmup + initial tunable knobs) — merged.
- Branch `feat/inference-perf-configurable-model` — the changes above; cache-on-by-default reproduces the hand-tuned sweep numbers within <1%.

**Comment by yuanchen8911** [comment]
### Follow-up finding: the readiness/timeout budget is hardcoded and blocks large models

A Qwen3-32B characterization run on GB200 (with the HF-token path from `feat/inference-perf-configurable-model` wired in) surfaced a fourth piece of scope:

- **HF-token path works** — no HTTP 429, authenticated downloads, workers did not crash-loop.
- **But the run failed on `InferenceWorkloadReadyTimeout` (10m, `pkg/defaults/timeouts.go`)**: loading 64 GB × 4 workers did not finish within the window, so the GPUs never engaged (0% utilization the entire run). The blocker moved from *rate-limiting* to *load time*.

This 10m budget is tuned for the 0.6B smoke-test model. Large-model characterization legitimately needs a longer load window, but it is **not** a one-line bump — the inference timeouts form a coordinated budget enforced by `pkg/defaults/timeouts_test.go`:

```
InferenceNamespaceTerminationWait (5m)
+ InferenceWorkloadReadyTimeout   (10m)   <-- fired
+ InferenceHealthTimeout          (5m)
+ InferencePerfPodTimeout         (5m)
+ InferencePerfJobTimeout         (15m)
= 40m  must be < CheckExecutionTimeout (45m)   and   CheckExecutionTimeout + K8sCleanupTimeout < 60m
```
plus the catalog entry's outer Job `timeout: 50m` (`activeDeadlineSeconds`).

**Add to scope (work item 4):** make the inference-perf timeout budget — especially `InferenceWorkloadReadyTimeout` — **configurable and scaled to model size**, wired per-accelerator/recipe alongside the other parameters. Larger models also benefit from weight pre-caching (ModelExpress server / shared PVC) and tensor-parallel (fewer concurrent downloaders), both already noted above.

**Comment by yuanchen8911** [comment]
### Follow-up: HF **IP-level** throttling blocks download-per-worker even *with* a token

Retried Qwen3-32B **and** Qwen3-8B on GB200 with the HF token wired in (verified: each worker container has `HF_TOKEN` via `secretKeyRef:aicr-hf-token/token`, Secret populated). Both still failed with **HTTP 429** — and the telling detail: the 429 hits the **first, ~few-KB file** (`LICENSE`), even for the small 8B model.

That is Hugging Face rate-limiting the **cluster's egress IP**, not an account/token limit. Note Qwen3-8B/32B are **Apache-2.0, ungated** — a token is **not required for access** (anonymous download works); it only raises *per-account* rate limits, and that does **not** bypass *per-IP* throttling. The download-per-worker pattern (4 workers × full weights, **multiplied by crash-loop re-downloads** — vLLM/dynamo re-fetches from scratch on each restart) hammers HF from a single NAT IP and triggers/extends the throttle. Retrying makes it worse.

**Implications for the large-model work items:**
- For ungated models the HF token is optional (helps rate limits only); for gated models (Llama/Gemma) it's required for access. Either way, token + longer readiness timeout are **not sufficient** when the egress IP is throttled.
- The model must be fetched **once and shared** — ModelExpress server or a pre-staged/shared PVC — **or** TP=1-worker (one downloader instead of N). This is **required**, not optional, for reliable large-model runs.
- Bonus: a shared cache also removes the per-run download entirely on warm clusters, which is the only way to keep runtimes bounded.

Until caching/TP lands, large-model characterization is blocked on HF egress throttling regardless of token/timeout.

**Comment by yuanchen8911** [comment]
### Caching design note: `imagePullPolicy` is the wrong layer — cache the *model weights*, not the image

A natural first instinct for "stop re-downloading" is `imagePullPolicy`, but that governs the **container image**, not the **model weights** — two separate layers:

| Layer | What | Governed by | The bottleneck? |
|-------|------|-------------|-----------------|
| Container image | `vllm-runtime:0.9.0` (nvcr.io) | `imagePullPolicy` | No — already node-cached (`IfNotPresent`); pod events show *"Container image already present on machine"* |
| Model weights | `Qwen/Qwen3-*` (huggingface.co) | dynamo/vLLM HF client **inside** the running container | **Yes** — the 64 GB×4 download that 429s |

So `imagePullPolicy` changes don't touch the HF download. The caching must happen at the weights layer.

**Empirical confirmation (GB200, Qwen3-8B):**
- One run succeeds after a long HF-throttle cooldown; a **second run right after re-throttles** (each run re-downloads the full model × 4 workers from one egress IP).
- Each **container restart re-downloads from scratch** — the HF cache lives in the container's writable layer, not a persistent volume — which amplifies load during a crash-loop.
- Net: the download-per-worker pattern caps us at ~one large-model run per cooldown. Reliable sweeps are impossible without caching.

**Options (in rough order of preference), all at the weights layer:**
1. **ModelExpress server** — dynamo's own model cache. Workers already try it first and fall back (*"Cannot connect to ModelExpress server… Using direct download"*). Deploy it → model fetched **once**, served to all workers; no per-worker/per-run HF hits.
2. **Shared HF-cache PVC** — pre-populate `~/.cache/huggingface` once, mount read-only into workers; also survives container restarts (fixes the crash-loop re-download).
3. **Model baked into an image** — *this* is where `imagePullPolicy: IfNotPresent` finally helps: a `model-cache` image pulled once and node-cached. Heaviest (large images), least flexible (model fixed at build).
4. **TP=1-worker** (one downloader vs N) — cuts per-run HF load 4× and is also the NVLink-characterization config; complements but doesn't replace a cache.

**Recommendation:** treat **ModelExpress (1) or a shared PVC (2)** as a prerequisite for the large-model characterization profile — not an optimization. A token + longer timeout (already added) are necessary but insufficient; only a shared weights cache makes repeated/large-model runs reliable.

**Comment by yuanchen8911** [comment]
### PVC model-weights cache validated end-to-end on a real cluster (GB200)

The PVC caching approach (option #2 above) is now implemented and validated against a live GB200 cluster (Qwen3-8B). The cache path works end-to-end:

- **PVC binds** — requires an explicit `StorageClass` on clusters with no default one (first attempt left the PVC `Pending`: *"no persistent volumes available … and no storage class is set"*; fixed by adding the `AICR_INFERENCE_PERF_MODEL_CACHE_STORAGE_CLASS` knob, set to `gp2` here).
- **Populate Job downloads the model once** — completed in ~32s, no HTTP 429, no PVC write-permission error.
- **Workers load offline from the PVC** — vLLM logs `HF_HUB_OFFLINE is True, replace model_id [Qwen/Qwen3-8B] to model_path [/model-cache/...]`; zero per-worker Hugging Face download, so no per-IP throttling.

**Implication:** with the cache proven, a large model (e.g. Qwen3-32B) becomes a one-line model-knob change — a single populate download, workers serve offline, no HF throttle. This removes the download-per-worker wall that blocked large-model characterization.

Knobs added on the `feat/inference-perf-configurable-model` branch (stacked on #1096): `AICR_INFERENCE_PERF_MODEL`, `AICR_INFERENCE_PERF_WORKLOAD_READY_TIMEOUT`, `AICR_INFERENCE_PERF_MODEL_CACHE_SIZE`, `AICR_INFERENCE_PERF_MODEL_CACHE_STORAGE_CLASS`, plus optional `HF_TOKEN` provisioning. Remaining for the cache: RWO + `WaitForFirstConsumer` pins all workers to one node (already the validator's behavior); multi-node would need RWX (or ModelExpress, option #1).
